# Generated by Django 2.2.12 on 2020-05-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('halaman', models.IntegerField()),
                ('harga', models.IntegerField()),
                ('tahun_terbit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penebit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerbit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penulis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_buku', models.ManyToManyField(to='shop.Buku')),
                ('id_pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pembeli')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField()),
                ('id_pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Pembeli')),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='id_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Kategori'),
        ),
        migrations.AddField(
            model_name='buku',
            name='id_penerbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Penebit'),
        ),
        migrations.AddField(
            model_name='buku',
            name='id_penulis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Penulis'),
        ),
    ]
