# Generated by Django 2.2.12 on 2020-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='invoice',
            field=models.CharField(default='####', max_length=50),
        ),
    ]
